CREATE TABLE es1_invoice_series (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    company_id  BIGINT       NOT NULL,
    code        VARCHAR(50)  NOT NULL,
    description VARCHAR(255) NOT NULL,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_es1 PRIMARY KEY (id),
    CONSTRAINT fk_es1_t4 FOREIGN KEY (company_id) REFERENCES t4_companies (id),
    CONSTRAINT uk_es1_code UNIQUE (company_id, code)
);

CREATE INDEX ix_es1_company ON es1_invoice_series (company_id);

CREATE TABLE es2_invoice_series_fiscal_year (
    id                   BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    series_id            BIGINT      NOT NULL,
    fiscal_year_id       BIGINT      NOT NULL,
    numbering_mode       SMALLINT    NOT NULL,
    active               BOOLEAN     NOT NULL DEFAULT TRUE,
    last_assigned_number BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT pk_es2 PRIMARY KEY (id),
    CONSTRAINT fk_es2_es1 FOREIGN KEY (series_id) REFERENCES es1_invoice_series (id),
    CONSTRAINT fk_es2_t7 FOREIGN KEY (fiscal_year_id) REFERENCES t7_fiscal_years (id),
    CONSTRAINT uk_es2_series_year UNIQUE (series_id, fiscal_year_id),
    CONSTRAINT ck_es2_numbering_mode CHECK (numbering_mode IN (1, 2)),
    CONSTRAINT ck_es2_last_number CHECK (last_assigned_number >= 0)
);

CREATE INDEX ix_es2_fiscal_year ON es2_invoice_series_fiscal_year (fiscal_year_id);
