CREATE TABLE es1_invoice_series (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    company_id  BIGINT       NOT NULL,
    code        VARCHAR(50)  NOT NULL,
    description VARCHAR(255) NOT NULL,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_es1 PRIMARY KEY (id),
    CONSTRAINT fk_es1_t6 FOREIGN KEY (company_id) REFERENCES t6_companies (id),
    CONSTRAINT uk_es1_code UNIQUE (company_id, code)
);

CREATE INDEX ix_es1_company ON es1_invoice_series (company_id);

CREATE TABLE es2_invoice_series_fiscal_year (
    id                   BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    series_id            BIGINT      NOT NULL,
    fiscal_year_id       BIGINT      NOT NULL,
    numbering_mode       SMALLINT    NOT NULL,
    active               BOOLEAN     NOT NULL DEFAULT TRUE,
    last_assigned_number BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT pk_es2 PRIMARY KEY (id),
    CONSTRAINT fk_es2_es1 FOREIGN KEY (series_id) REFERENCES es1_invoice_series (id),
    CONSTRAINT fk_es2_t9 FOREIGN KEY (fiscal_year_id) REFERENCES t9_fiscal_years (id),
    CONSTRAINT uk_es2_series_year UNIQUE (series_id, fiscal_year_id),
    CONSTRAINT ck_es2_numbering_mode CHECK (numbering_mode IN (1, 2)),
    CONSTRAINT ck_es2_last_number CHECK (last_assigned_number >= 0)
);

CREATE INDEX ix_es2_fiscal_year ON es2_invoice_series_fiscal_year (fiscal_year_id);

INSERT INTO t5_legal_forms (country_alpha2_code, code, description, is_organization) VALUES
    ('ES', 'EI',    'Empresario individual',                   FALSE),
    ('ES', 'PA',    'Profesional autónomo',                    FALSE),
    ('ES', 'ERL',   'Emprendedor de Responsabilidad Limitada', FALSE),
    ('ES', 'SL',    'Sociedad Limitada',                       TRUE),
    ('ES', 'SLU',   'Sociedad Limitada Unipersonal',           TRUE),
    ('ES', 'SA',    'Sociedad Anónima',                        TRUE),
    ('ES', 'SAU',   'Sociedad Anónima Unipersonal',            TRUE),
    ('ES', 'SColl', 'Sociedad Colectiva',                      TRUE),
    ('ES', 'SCom',  'Sociedad Comanditaria Simple',            TRUE),
    ('ES', 'SComA', 'Sociedad Comanditaria por Acciones',      TRUE),
    ('ES', 'SCoop', 'Sociedad Cooperativa',                    TRUE),
    ('ES', 'SLL',   'Sociedad Limitada Laboral',               TRUE),
    ('ES', 'SAL',   'Sociedad Anónima Laboral',                TRUE),
    ('ES', 'SC',    'Sociedad Civil',                          TRUE),
    ('ES', 'CB',    'Comunidad de Bienes',                     TRUE),
    ('ES', 'AIE',   'Agrupación de Interés Económico',         TRUE),
    ('ES', 'SAT',   'Sociedad Agraria de Transformación',      TRUE);

INSERT INTO t4_country_currency (country_alpha2_code, currency_numeric_code) VALUES
    ('ES', 978);
