plugins {
    alias(libs.plugins.lombok.freefair)
    alias(libs.plugins.javafx)
}


javafx {
    version = libs.versions.javafx.get()
    modules = ["javafx.controls", "javafx.fxml"]
}

dependencies {
    implementation(project(":arume-core"))
    implementation(libs.spring.boot)
    implementation(libs.atlantafx.base)
    implementation(libs.ikonli.javafx)
    implementation(libs.ikonli.fontawesome5)
    implementation(libs.ikonli.materialdesign2)
    implementation(libs.slf4j.api)
    implementation(libs.snakeyaml)

    testImplementation(libs.junit.jupiter)
    testImplementation(libs.hamcrest)
    testImplementation(libs.testfx.junit5)
    testRuntimeOnly(libs.junit.platform.launcher)
}
