[versions]
atlantafx = "2.1.0"
ikonli = "12.3.1"
flyway = "12.10.0"
h2 = "2.4.240"

javafx = "25"
junit-jupiter = "5.12.2"
hamcrest = "2.2"
testfx = "4.0.18"
lombok-freefair = "9.5.0"
mybatis-spring-boot = "4.0.1"
mybatis-generator = "2.0.0"
mybatis-generator-lombok = "1.0"
mybatis-jsr310 = "1.0.2"
mybatis-plugin = "2.5"
snakeyaml = "2.4"
spring-boot = "4.1.0"

[libraries]
atlantafx-base = { module = "io.github.mkpaz:atlantafx-base", version.ref = "atlantafx" }
ikonli-javafx = { module = "org.kordamp.ikonli:ikonli-javafx", version.ref = "ikonli" }
ikonli-fontawesome5 = { module = "org.kordamp.ikonli:ikonli-fontawesome5-pack", version.ref = "ikonli" }
ikonli-materialdesign2 = { module = "org.kordamp.ikonli:ikonli-materialdesign2-pack", version.ref = "ikonli" }
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
hamcrest = { module = "org.hamcrest:hamcrest", version.ref = "hamcrest" }
testfx-junit5 = { module = "org.testfx:testfx-junit5", version.ref = "testfx" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version = "1.12.2" }
spring-boot = { module = "org.springframework.boot:spring-boot", version.ref = "spring-boot" }
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter", version.ref = "spring-boot" }
spring-boot-starter-jdbc = { module = "org.springframework.boot:spring-boot-starter-jdbc", version.ref = "spring-boot" }
mybatis-generator-lombok-plugin = { module = "com.softwareloop:mybatis-generator-lombok-plugin", version.ref = "mybatis-generator-lombok" }
mybatis-generator-core = { module = "org.mybatis.generator:mybatis-generator-core", version.ref = "mybatis-generator" }
mybatis-jsr310 = { module = "org.mybatis:mybatis-typehandlers-jsr310", version.ref = "mybatis-jsr310" }
mybatis-spring-boot-starter = { module = "org.mybatis.spring.boot:mybatis-spring-boot-starter", version.ref = "mybatis-spring-boot" }
slf4j-api = { module = "org.slf4j:slf4j-api", version = "2.0.17" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }

[plugins]
javafx = { id = "org.openjfx.javafxplugin", version = "0.1.0" }

lombok-freefair = { id = "io.freefair.lombok", version.ref = "lombok-freefair" }
mybatis-generator = { id = "com.qqviaja.gradle.MybatisGenerator", version.ref = "mybatis-plugin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
