plugins {
    alias(libs.plugins.lombok.freefair)
    alias(libs.plugins.spring.boot)
    alias(libs.plugins.javafx)
}

javafx {
    version = libs.versions.javafx.get()
    modules = ["javafx.controls", "javafx.fxml"]
}

springBoot {
    mainClass = "com.angazo.arume.app.ArumeApp"
}

tasks.named("bootRun") {
    jvmArgs = ["--enable-native-access=ALL-UNNAMED"]
}

dependencies {

    // Local modules
    implementation(project(":arume-core"))
    implementation(project(":arume-db"))
    implementation(project(":arume-es"))
    implementation(project(":arume-uk"))
    implementation(project(":arume-ui"))
    implementation(libs.mybatis.spring.boot.starter)

    // Spring Boot application
    implementation(libs.spring.boot.starter)

    // H2 Database driver
    runtimeOnly(libs.h2)

    // Test dependencies
    testImplementation(libs.junit.jupiter)
    testImplementation(libs.flyway.core)
    testImplementation(libs.h2)
    testImplementation(libs.spring.boot.starter.test)
    testRuntimeOnly(libs.junit.platform.launcher)
}


