CREATE TABLE t0_app_config (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    config_key   VARCHAR(255) NOT NULL,
    config_value VARCHAR(1024),
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_t0 PRIMARY KEY (id)
);
