CREATE TABLE t4_companies (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    is_legal_person            BOOLEAN      NOT NULL,
    primary_fiscal_jurisdiction VARCHAR(3)  NOT NULL,
    primary_fiscal_id          VARCHAR(100) NOT NULL,
    legal_form_jurisdiction    VARCHAR(3)   NOT NULL,
    legal_form_code            VARCHAR(100) NOT NULL,
    created_at                 TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_t4 PRIMARY KEY (id),
    CONSTRAINT uk_t4_fiscal_id UNIQUE (primary_fiscal_jurisdiction, primary_fiscal_id),
    CONSTRAINT fk_t4_t1 FOREIGN KEY (primary_fiscal_jurisdiction) REFERENCES t1_countries (alpha3_code),
    CONSTRAINT fk_t4_t1_2 FOREIGN KEY (legal_form_jurisdiction) REFERENCES t1_countries (alpha3_code)
);

CREATE TABLE t5_company_profiles (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    company_id        BIGINT       NOT NULL,
    legal_name        VARCHAR(255) NOT NULL,
    fiscal_residence  VARCHAR(3)   NOT NULL,
    domicile          VARCHAR(1024) NOT NULL,
    valid_from        DATE         NOT NULL,
    valid_to          DATE,
    CONSTRAINT pk_t5 PRIMARY KEY (id),
    CONSTRAINT fk_t5_t4 FOREIGN KEY (company_id) REFERENCES t4_companies (id),
    CONSTRAINT uk_t5_company_valid_from UNIQUE (company_id, valid_from),
    CONSTRAINT ck_t5_validity CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

CREATE INDEX ix_t5_company_validity ON t5_company_profiles (company_id, valid_from, valid_to);

CREATE TABLE t6_company_tax_registrations (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    company_id  BIGINT       NOT NULL,
    jurisdiction VARCHAR(3)  NOT NULL,
    tax_id      VARCHAR(100) NOT NULL,
    valid_from  DATE         NOT NULL,
    valid_to    DATE,
    CONSTRAINT pk_t6 PRIMARY KEY (id),
    CONSTRAINT fk_t6_t4 FOREIGN KEY (company_id) REFERENCES t4_companies (id),
    CONSTRAINT uk_t6_registration_start UNIQUE (company_id, jurisdiction, tax_id, valid_from),
    CONSTRAINT ck_t6_validity CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

CREATE INDEX ix_t6_company_jurisdiction ON t6_company_tax_registrations (company_id, jurisdiction, valid_from);

CREATE TABLE t7_fiscal_years (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    company_id  BIGINT       NOT NULL,
    start_date  DATE         NOT NULL,
    end_date    DATE         NOT NULL,
    status      VARCHAR(16)  NOT NULL,
    label       VARCHAR(100) NOT NULL,
    CONSTRAINT pk_t7 PRIMARY KEY (id),
    CONSTRAINT fk_t7_t4 FOREIGN KEY (company_id) REFERENCES t4_companies (id),
    CONSTRAINT uk_t7_company_start UNIQUE (company_id, start_date),
    CONSTRAINT ck_t7_dates CHECK (end_date >= start_date),
    CONSTRAINT ck_t7_status CHECK (status IN ('OPEN', 'CLOSED'))
);

CREATE INDEX ix_t7_company_dates ON t7_fiscal_years (company_id, start_date, end_date);
