CREATE TABLE t0_i18n (
    language_code VARCHAR(2)   NOT NULL,
    name          VARCHAR(100) NOT NULL,
    CONSTRAINT pk_t0 PRIMARY KEY (language_code)
);

CREATE TABLE t1_countries (
    alpha2_code  VARCHAR(2) NOT NULL,
    alpha3_code  VARCHAR(3) NOT NULL,
    numeric_code SMALLINT   NOT NULL,
    CONSTRAINT pk_t1 PRIMARY KEY (alpha2_code),
    CONSTRAINT uk_t1_alpha3 UNIQUE (alpha3_code),
    CONSTRAINT uk_t1_numeric UNIQUE (numeric_code)
);

CREATE TABLE t2_country_names (
    country_alpha2_code VARCHAR(2)   NOT NULL,
    language_code       VARCHAR(2)   NOT NULL,
    name                VARCHAR(100) NOT NULL,
    CONSTRAINT pk_t2 PRIMARY KEY (country_alpha2_code, language_code),
    CONSTRAINT fk_t2_t1 FOREIGN KEY (country_alpha2_code) REFERENCES t1_countries (alpha2_code),
    CONSTRAINT fk_t2_t0 FOREIGN KEY (language_code) REFERENCES t0_i18n (language_code)
);

CREATE TABLE t3_currencies (
    numeric_code SMALLINT     NOT NULL,
    alpha3_code  VARCHAR(3)   NOT NULL,
    name         VARCHAR(100) NOT NULL,
    symbol       VARCHAR(8)   NOT NULL,
    CONSTRAINT pk_t3 PRIMARY KEY (numeric_code),
    CONSTRAINT uk_t3_alpha3 UNIQUE (alpha3_code)
);

CREATE TABLE t4_country_currency (
    country_alpha2_code   VARCHAR(2) NOT NULL,
    currency_numeric_code SMALLINT   NOT NULL,
    CONSTRAINT pk_t4 PRIMARY KEY (country_alpha2_code, currency_numeric_code),
    CONSTRAINT fk_t4_t1 FOREIGN KEY (country_alpha2_code) REFERENCES t1_countries (alpha2_code),
    CONSTRAINT fk_t4_t3 FOREIGN KEY (currency_numeric_code) REFERENCES t3_currencies (numeric_code)
);

CREATE TABLE t5_legal_forms (
    country_alpha2_code VARCHAR(2)   NOT NULL,
    is_legal_person     BOOLEAN      NOT NULL,
    code                VARCHAR(100) NOT NULL,
    description         VARCHAR(255) NOT NULL,
    CONSTRAINT pk_t5 PRIMARY KEY (country_alpha2_code, is_legal_person, code),
    CONSTRAINT fk_t5_t1 FOREIGN KEY (country_alpha2_code) REFERENCES t1_countries (alpha2_code)
);

CREATE TABLE t6_companies (
    id                          BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    is_legal_person             BOOLEAN      NOT NULL,
    primary_fiscal_jurisdiction VARCHAR(2)   NOT NULL,
    primary_fiscal_id           VARCHAR(100) NOT NULL,
    legal_form_jurisdiction     VARCHAR(2)   NOT NULL,
    legal_form_code             VARCHAR(100) NOT NULL,
    created_at                  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_t6 PRIMARY KEY (id),
    CONSTRAINT uk_t6_fiscal_id UNIQUE (primary_fiscal_jurisdiction, primary_fiscal_id),
    CONSTRAINT fk_t6_t1 FOREIGN KEY (primary_fiscal_jurisdiction) REFERENCES t1_countries (alpha2_code),
    CONSTRAINT fk_t6_t1_2 FOREIGN KEY (legal_form_jurisdiction) REFERENCES t1_countries (alpha2_code),
    CONSTRAINT fk_t6_t5 FOREIGN KEY (legal_form_jurisdiction, is_legal_person, legal_form_code)
        REFERENCES t5_legal_forms (country_alpha2_code, is_legal_person, code)
);

CREATE TABLE t7_company_profiles (
    id               BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    company_id       BIGINT        NOT NULL,
    legal_name       VARCHAR(255)  NOT NULL,
    fiscal_residence VARCHAR(2)    NOT NULL,
    domicile         VARCHAR(1024) NOT NULL,
    valid_from       DATE          NOT NULL,
    valid_to         DATE,
    CONSTRAINT pk_t7 PRIMARY KEY (id),
    CONSTRAINT fk_t7_t6 FOREIGN KEY (company_id) REFERENCES t6_companies (id),
    CONSTRAINT fk_t7_t1 FOREIGN KEY (fiscal_residence) REFERENCES t1_countries (alpha2_code),
    CONSTRAINT uk_t7_company_valid_from UNIQUE (company_id, valid_from),
    CONSTRAINT ck_t7_validity CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

CREATE INDEX ix_t7_company_validity ON t7_company_profiles (company_id, valid_from, valid_to);

CREATE TABLE t8_company_tax_registrations (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    company_id   BIGINT       NOT NULL,
    jurisdiction VARCHAR(2)   NOT NULL,
    tax_id       VARCHAR(100) NOT NULL,
    valid_from   DATE         NOT NULL,
    valid_to     DATE,
    CONSTRAINT pk_t8 PRIMARY KEY (id),
    CONSTRAINT fk_t8_t6 FOREIGN KEY (company_id) REFERENCES t6_companies (id),
    CONSTRAINT fk_t8_t1 FOREIGN KEY (jurisdiction) REFERENCES t1_countries (alpha2_code),
    CONSTRAINT uk_t8_registration_start UNIQUE (company_id, jurisdiction, tax_id, valid_from),
    CONSTRAINT ck_t8_validity CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

CREATE INDEX ix_t8_company_jurisdiction ON t8_company_tax_registrations (company_id, jurisdiction, valid_from);

CREATE TABLE t9_fiscal_years (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    company_id BIGINT       NOT NULL,
    start_date DATE         NOT NULL,
    end_date   DATE         NOT NULL,
    status     VARCHAR(16)  NOT NULL,
    label      VARCHAR(100) NOT NULL,
    CONSTRAINT pk_t9 PRIMARY KEY (id),
    CONSTRAINT fk_t9_t6 FOREIGN KEY (company_id) REFERENCES t6_companies (id),
    CONSTRAINT uk_t9_company_start UNIQUE (company_id, start_date),
    CONSTRAINT ck_t9_dates CHECK (end_date >= start_date),
    CONSTRAINT ck_t9_status CHECK (status IN ('OPEN', 'CLOSED'))
);

CREATE INDEX ix_t9_company_dates ON t9_fiscal_years (company_id, start_date, end_date);

INSERT INTO t0_i18n (language_code, name) VALUES
    ('en', 'English'),
    ('es', 'Spanish');

INSERT INTO t1_countries (alpha2_code, alpha3_code, numeric_code) VALUES
    ('ES', 'ESP', 724),
    ('GB', 'GBR', 826),
    ('US', 'USA', 840),
    ('CL', 'CHL', 152),
    ('SG', 'SGP', 702),
    ('AU', 'AUS', 36),
    ('ZA', 'ZAF', 710);

INSERT INTO t2_country_names (country_alpha2_code, language_code, name) VALUES
    ('ES', 'en', 'Spain'),
    ('GB', 'en', 'United Kingdom'),
    ('US', 'en', 'United States'),
    ('CL', 'en', 'Chile'),
    ('SG', 'en', 'Singapore'),
    ('AU', 'en', 'Australia'),
    ('ZA', 'en', 'South Africa'),
    ('ES', 'es', 'España'),
    ('GB', 'es', 'Reino Unido'),
    ('US', 'es', 'Estados Unidos'),
    ('CL', 'es', 'Chile'),
    ('SG', 'es', 'Singapur'),
    ('AU', 'es', 'Australia'),
    ('ZA', 'es', 'Sudáfrica');

INSERT INTO t3_currencies (numeric_code, alpha3_code, name, symbol) VALUES
    (978, 'EUR', 'Euro', '€'),
    (826, 'GBP', 'Pound Sterling', '£'),
    (840, 'USD', 'US Dollar', '$'),
    (152, 'CLP', 'Chilean Peso', '$'),
    (990, 'CLF', 'Unidad de Fomento', 'UF'),
    (702, 'SGD', 'Singapore Dollar', '$'),
    (36, 'AUD', 'Australian Dollar', '$'),
    (710, 'ZAR', 'Rand', 'R');


